### ISSUE TITLE
I use a 3em and it would be nice to have 3 single indicators

### ISSUE THREAD

**Issue by testpaul999** [maloo0/homebridge-shelly-consumption#1]
**Is your feature request related to a problem? Please describe:**

no

**Describe the solution you'd like:**

I use a 3em and it would be nice to have 3 single indicators

**Describe alternatives you've considered:**

configurable within the configuration 

**Additional context:**

Great job until today 👍🏻🙂

**Comment by maloo0** [comment]
Hello testpaul999,

Thanks a lot for opening this issue and reporting your suggestion for enhancement!

I just added a detailed description of the plugin to GitHub now. If I understood you correctly, this is already provided by my implementation. 
Adding single indicators for the single channels to Homekit is possible by adding a further device with the same ip address but another channel selection. On that way, it is possible too, to add further indicators for different combinations of channels.

This is described more detailed in the README (on the startpage of my Git repository) and I additionally provided an example for this there.

I hope that I understood it right and I could help you with this.
If you have any further questions or suggestions, feel free to contact me.

Thanks a lot,
maloo0

**Comment by testpaul999** [comment]
Hi, thx for the answer.
This solution is good for me.

Regards

Viele Grüße

Jens-Uwe Franz

Am 25.03.2021 um 22:46 schrieb maloo0 ***@***.***>:

﻿

Hello testpaul999,

Thanks a lot for opening this issue and reporting your suggestion for enhancement!

I just added a detailed description of the plugin to GitHub now. If I understood you correctly, this is already provided by my implementation.
Adding single indicators for the single channels to Homekit is possible by adding a further device with the same ip address but another channel selection. On that way, it is possible too, to add further indicators for different combinations of channels.

This is described more detailed in the README (on the startpage of my Git repository) and I additionally provided an example for this there.

I hope that I understood it right and I could help you with this.
If you have any further questions or suggestions, feel free to contact me.

Thanks a lot,
maloo0
